print("git init")
print("New function")
print("d/Git_Test")
print("bug fix in master")
print("New function")
print("CloudMusic/Git_Test")
print("d/CloudMusic/Git_Test")
print("hello world")
print("new update ")